### ISSUE TITLE
'rails fake_data' fails right after database setup

### ISSUE THREAD

**Issue by myhro** [lobsters/lobsters#1230]
I was following the [README instructions][1], trying to add the sample data after the [database setup][2], when the process failed with the error below:

```
$ rails fake_data
W, [2023-12-13T20:04:20.145440 #89198]  WARN -- : heinous_inline_partial initialized, found: {"app/views/comments/_threads.html.erb"=>"app/views/comments/_comment.html.erb"}
Users .rails aborted!
NoMethodError: undefined method `id' for nil:NilClass
/home/myhro/Documents/github.com/lobsters/lobsters/app/models/user.rb:433:in `block in grant_moderatorship_by_user!'
/home/myhro/Documents/github.com/lobsters/lobsters/app/models/user.rb:428:in `grant_moderatorship_by_user!'
/home/myhro/Documents/github.com/lobsters/lobsters/lib/tasks/fake_data.rake:35:in `block in generate'
/home/myhro/Documents/github.com/lobsters/lobsters/lib/tasks/fake_data.rake:15:in `upto'
/home/myhro/Documents/github.com/lobsters/lobsters/lib/tasks/fake_data.rake:15:in `each'
/home/myhro/Documents/github.com/lobsters/lobsters/lib/tasks/fake_data.rake:15:in `generate'
/home/myhro/Documents/github.com/lobsters/lobsters/lib/tasks/fake_data.rake:294:in `block in <top (required)>'
Tasks: TOP => fake_data
(See full trace by running task with --trace)
```

This happens because, as the database is empty right after its setup, there's no moderator to be sampled on:

https://github.com/lobsters/lobsters/blob/ff19562026138635d7fe597900b1453366d2e58b/lib/tasks/fake_data.rake#L17

Which leads to `grant_moderatorship_by_user` being called with a `nil` argument:

https://github.com/lobsters/lobsters/blob/ff19562026138635d7fe597900b1453366d2e58b/lib/tasks/fake_data.rake#L35

Running `rails db:seed` before trying to create fake data fixes the issue, as an admin/moderator is created in this step:

```
$ rails db:seed
W, [2023-12-13T20:11:22.905455 #89947]  WARN -- : heinous_inline_partial initialized, found: {"app/views/comments/_threads.html.erb"=>"app/views/comments/_comment.html.erb
"}
created:
  * an admin with username/password of test/test
  * inactive-user for disowned comments by deleted users
  * a test tag

If this is a dev environment, you probably want to run `rails fake_data`
If this is production, you want to run `rails console` to rename your admin. Edit your category, and tag on-site.
$ rails fake_data
W, [2023-12-13T20:11:27.885614 #90081]  WARN -- : heinous_inline_partial initialized, found: {"app/views/comments/_threads.html.erb"=>"app/views/comments/_comment.html.erb"}
Users ...................................................
Categories .....
Stories ....................................................................................................
SavedStories ..........
Comments ..............................................................................................................
Comment Flags ....................................................................................................................................................................................................................................................................................
Story Flags ..............................................................................................................
Hats .........................
Comments (delete/undelete) ....................................................................................................................................................................................................................................................................................
Delete stories by submitter/mods .
Doff hats ..
Ban Users ..
Merge Stories .....
Editing Stories .....
Deleting stories .....
```

What would be a reasonable fix for this issue? I thought about documenting this requirement in the README, but I realized that the `db:seed` task was [recently removed from the development setup instructions][3]. Should we re-add to there? Or should the `fake_data` task actually create a moderator by itself?

[1]: https://github.com/lobsters/lobsters/tree/ff19562026138635d7fe597900b1453366d2e58b#development-setup
[2]: https://github.com/lobsters/lobsters/blob/ff19562026138635d7fe597900b1453366d2e58b/bin/setup#L29-L30
[3]: https://github.com/lobsters/lobsters/commit/1f4547d2b9146acaf0f5902802d81de69a7101f9#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

**Comment by pushcx** [comment]
Oops, I was trying to streamline the process when I removed it. I appreciate you being willing to PR it, but it’s such a small fix that looking at it was as fast as fixing it. Thanks for reporting!
