### ISSUE TITLE
mariadb deadlocks

### ISSUE THREAD

**Issue by pushcx** [lobsters/lobsters#1238]
https://github.com/lobsters/lobsters/issues/1612

I wanted to cross-post this bug here because I can't just move it. It's in the Rails code, but all the tech details are already over there.

This deadlock happens because comment (and, much more rarely, story) creation is locking tables in a different order than vote creation (slash updating?). Maybe because of assigning the user's initial upvote or some memoized value like score/karma/votes/number of comments/etc.

The job here is to vote/unvote stories and comments in dev, and read the rails server log for the order that tables are touched in. Then same for story and comment posting. I am almost certain that will uncover tables accessed in a different order. Just posting those notes as a comment here would be very helpful!

If that is indeed the cause of the deadlock, then we have to shlep through the controllers and callbacks to figure out how to reorder, simplify, or break apart the transactions. Probably nothing even needs to be in a transaction, we're just getting it from Rails by default. But since I touched all the score code in 20c15907 I think voting should always work by doing `score += 1` or `score = sum(votes)` rather than an unsafe `select ... add 1 in ruby ... update`, so a transaction is unneeded.

**Comment by pushcx** [comment]
This got much worse in the last couple days because I had the page cache disabled to correctly show the banner pointing UK users to the [call for help with their OSA](https://lobste.rs/s/ukosa1). Instead of being a once-a-month bug it was once or twice a day.

Maybe the most straightforward fix to this would be to move `Story#calculated_hotness` and `Comment#calculated_confidence` into idempotent database queries, so we'd have these code paths insert/update/delete votes and then call `story.calculate_confidence!` which would issue a minimal `update`. That would eliminate the need to lock tables data is read and written back in a transaction.

**Comment by pushcx** [comment]
Nope, got a deadlock on a new comment this morning:

```
An ActiveRecord::Deadlocked occurred in comments#create:

  Trilogy::ProtocolError: 1213: Deadlock found when trying to get lock; try restarting transaction (trilogy_read_row)
  app/controllers/comments_controller.rb:50:in 'CommentsController#create'
```

**Comment by pushcx** [comment]
by requests, all hits from a couple seconds before the exception through the deadlock

```
{"method":"GET","path":"/~Vanishftw","format":"*/*","controller":"UsersController","action":"show","status":404,"allocations":2385,"duration":10.78,"view":3.95,"db":3.12,"timestamp":"2025-02-1
1T07:07:41.542Z","params":{},"exception":null,"exception_message":null,"remote_ip":"","user_id":0,"username":"nobody"}
{"method":"GET","path":"/~bystagedright","format":"*/*","controller":"UsersController","action":"show","status":404,"allocations":2391,"duration":11.49,"view":3.64,"db":4.04,"timestamp":"2025-
02-11T07:07:41.617Z","params":{},"exception":null,"exception_message":null,"remote_ip":"","user_id":0,"username":"nobody"}
{"method":"GET","path":"/~rajaemoumen","format":"*/*","controller":"UsersController","action":"show","status":404,"allocations":2269,"duration":11.17,"view":3.22,"db":3.91,"timestamp":"2025-02
-11T07:07:41.780Z","params":{},"exception":null,"exception_message":null,"remote_ip":"","user_id":0,"username":"nobody"}
{"method":"GET","path":"/s/xruava","format":"html","controller":"StoriesController","action":"show","status":200,"allocations":8678,"duration":60.22,"view":24.01,"db":21.73,"timestamp":"2025-0
2-11T07:07:42.005Z","params":{},"exception":null,"exception_message":null,"remote_ip":"","user_id":0,"username":"nobody"}
{"method":"GET","path":"/t/pdf.rss","format":"rss","controller":"HomeController","action":"single_tag","status":200,"allocations":43033,"duration":260.84,"view":20.49,"db":129.41,"timestamp":"
2025-02-11T07:07:43.124Z","params":{},"exception":null,"exception_message":null,"remote_ip":"","user_id":0,"username":"nobody"}
{"method":"GET","path":"/","format":"html","controller":"HomeController","action":"index","status":200,"allocations":21315,"duration":47.71,"view":30.89,"db":1.41,"timestamp":"2025-02-11T07:07
:44.013Z","params":{},"exception":null,"exception_message":null,"remote_ip":"","user_id":0,"username":"nobody"}
I, [2025-02-11T07:07:44.090060 #1312865]  INFO -- : Redirected to https://lobste.rs/~Hawoth_Lifestyle
I, [2025-02-11T07:07:44.090217 #1312865]  INFO -- : Completed 301 Moved Permanently in 1ms
{"method":"GET","path":"/s/1wiec3/reverse_engineering_register_codes_for","format":"*/*","controller":"StoriesController","action":"show","status":200,"allocations":8805,"duration":68.48,"view
":20.72,"db":36.42,"timestamp":"2025-02-11T07:07:44.476Z","params":{},"exception":null,"exception_message":null,"remote_ip":"","user_id":0,"username":"nobody"}
{"method":"GET","path":"/s/uoiosa/undergraduate_invents_faster_hash_table","format":"html","controller":"StoriesController","action":"show","status":200,"allocations":13667,"duration":67.24,"v
iew":35.46,"db":21.84,"timestamp":"2025-02-11T07:07:44.524Z","params":{},"exception":null,"exception_message":null,"remote_ip":"","user_id":0,"username":"no
body"}
{"method":"GET","path":"/rss","format":"rss","controller":"HomeController","action":"index","status":200,"allocations":6852,"duration":20.24,"view":0.46,"db":0.69,"timestamp":"2025-02-11T07:07
:44.547Z","params":{},"exception":null,"exception_message":null,"remote_ip":"","user_id":0,"username":"nobody"}
{"method":"GET","path":"/rss","format":"rss","controller":"HomeController","action":"index","status":200,"allocations":6837,"duration":30.43,"view":0.71,"db":1.56,"timestamp":"2025-02-11T07:07
:44.743Z","params":{},"exception":null,"exception_message":null,"remote_ip":"","user_id":0,"username":"nobody"}
{"method":"GET","path":"/rss","format":"rss","controller":"HomeController","action":"index","status":200,"allocations":10574,"duration":69.77,"view":0.41,"db":3.32,"timestamp":"2025-02-11T07:0
7:44.761Z","params":{},"exception":null,"exception_message":null,"remote_ip":"","user_id":0,"username":"nobody"}
{"method":"POST","path":"/comments","format":"*/*","controller":"CommentsController","action":"create","status":500,"allocations":4343,"duration":113.74,"view":0.0,"db":76.18,"timestamp":"2025
-02-11T07:07:44.793Z","params":{"authenticity_token":"[FILTERED]","story_id":"ymszmx","_method":"post","parent_comment_short_id":"65eaqp","comment":"Dropping the lang is bad for accessibility.
 Without the doctype it’s not valid standards mode HTML. The charset is necessary if you have any non-ASCII characters. The viewport tag is needed for proper rendering on mobile.","show_tree_l
ines":"true"},"exception":"ActiveRecord::Deadlocked","exception_message":"Trilogy::ProtocolError: 1213: Deadlock found when trying to get lock; try restarting transaction (trilogy_read_row)","
remote_ip":"","user_id":14657,"username":"xigoi"}
{"method":"GET","path":"/s/vdd1rq/what_s_new_dsq_commandline_tool_for","format":"*/*","controller":"StoriesController","action":"show","status":200,"allocations":22013,"duration":157.0,"view":
55.0,"db":90.22,"timestamp":"2025-02-11T07:07:44.818Z","params":{},"exception":null,"exception_message":null,"remote_ip":"","user_id":0,"username":"nobody"}
{"method":"POST","path":"/comments","format":"*/*","controller":"CommentsController","action":"create","status":200,"allocations":9674,"duration":256.37,"view":3.19,"db":173.6,"timestamp":"202
5-02-11T07:07:44.922Z","params":{"authenticity_token":"[FILTERED]","story_id":"ymszmx","_method":"post","parent_comment_short_id":"65eaqp","comment":"Dropping the lang is bad for accessibility
. Without the doctype it’s not valid standards mode HTML. The charset is necessary if you have any non-ASCII characters. The viewport tag is needed for proper rendering on mobile.","show_tree_
lines":"true"},"exception":null,"exception_message":null,"remote_ip":"","user_id":14657,"username":"xigoi"}
E, [2025-02-11T07:07:44.944264 #1313181] ERROR -- :
ActiveRecord::Deadlocked (Trilogy::ProtocolError: 1213: Deadlock found when trying to get lock; try restarting transaction (trilogy_read_row))
Caused by: Trilogy::ProtocolError (1213: Deadlock found when trying to get lock; try restarting transaction (trilogy_read_row))

Information for: ActiveRecord::Deadlocked (Trilogy::ProtocolError: 1213: Deadlock found when trying to get lock; try restarting transaction (trilogy_read_row)):


Information for cause: Trilogy::ProtocolError (1213: Deadlock found when trying to get lock; try restarting transaction (trilogy_read_row)):

app/controllers/comments_controller.rb:50:in 'CommentsController#create'
app/controllers/application_controller.rb:153:in 'ApplicationController#n_plus_one_detection'
{"method":"GET","path":"/rss","format":"rss","controller":"HomeController","action":"index","status":200,"allocations":6847,"duration":20.64,"view":0.41,"db":0.61,"timestamp":"2025-02-11T07:07
:44.971Z","params":{},"exception":null,"exception_message":null,"remote_ip":"","user_id":0,"username":"nobody"}
{"method":"GET","path":"/rss","format":"rss","controller":"HomeController","action":"index","status":200,"allocations":6862,"duration":26.4,"view":0.5,"db":0.69,"timestamp":"2025-02-11T07:07:4
4.990Z","params":{},"exception":null,"exception_message":null,"remote_ip":"","user_id":0,"username":"nobody"}     

```

**Comment by pushcx** [comment]
Interestingly, it looks like the user is double-posting (two identical comment creation actions ~.25s apart) and the comment creation is deadlocking itself. I know I've seen that it happens when someone creates a comment at the same time as a vote; I hadn't seen this before.

**Comment by freddyb** [comment]
Found this issue while searching for something else, I think this here and other good first mariadb issues can be closed (or need to he rephrased) after the DB change to sqlite.
