### ISSUE TITLE
local set-up following README doesn't make success

### ISSUE THREAD

**Issue by 16dango** [lobsters/lobsters#1265]
Hi, I'm new to contribute on OSS.

I'd like to work on this
https://github.com/lobsters/lobsters/issues/1264

I'd like to join your project "lobsters" and started preparing local develop environment yesterday.
I followed all of README for that but I'm struggling on this step

> rails fake_data

the error comes up like below

```
KeyError (key not found: :Field
Did you mean?  :"Field\x00\x00"):

app/models/keystore.rb:18:in `value_for'
app/helpers/traffic_helper.rb:59:in `cached_current_intensity'
app/controllers/application_controller.rb:109:in `set_traffic_style'
```

Is this because of my missed set-up on local or not.
Thank you.

**Comment by pushcx** [comment]
Could you paste what you have in `app/helpers/traffic_helper.rb` line `59`? It _should_ be `Keystore.value_for("traffic:intensity") || 0.5` and I can’t imagine how you’re getting this error unless that line has changed.

**Comment by pushcx** [comment]
This has been inactive for a while, but please reopen with info if you need more help. Or come by [IRC sometime](https://lobste.rs/chat), a live back-and-forth might be easiest.

**Comment by pushcx** [comment]
This is solid progress and a clear error message. This error is saying that you need to edit `config/database.yml` (both the `development` and `test` sections) to match your local mariadb. If those match, you may need to make sure mariadb is running. (MariaDB is a fork of MySQL and uses the same driver, so you will often see "mysql" in options and messages.)

**Comment by pushcx** [comment]
#1302 is going to improve `config/database.yml`, I wanted to mention it to you before it's merged in case the example is useful to you right now.

I'm now also [streaming Lobsters office hours](https://push.cx/stream) as another option to get help live.
