### ISSUE TITLE
500 on mastodon_disconnect

### ISSUE THREAD

**Issue by thombles** [lobsters/lobsters#1395]
I became tired of microblogging and shut down my Mastodon instance. I tried to remove the connection from my lobsters profile (thombles) and received a 500 error:

![mastodon_disconnect](https://github.com/user-attachments/assets/85ab1f8d-99aa-4306-8a93-a0db8f80db95)

**Comment by pushcx** [comment]
Ah, I got an exception for this that's in my queue to look into:

```
  undefined method `body' for nil
  app/models/mastodon_app.rb:115:in `revoke_token'
  app/controllers/settings_controller.rb:226:in `mastodon_disconnect'
  app/controllers/application_controller.rb:198:in `n_plus_one_detection'
```

A different user got a second exception that's probably related:

```
  SSL_connect returned=1 errno=0 peeraddr=[IP address for mastodon server redacted] state=error: tlsv1 alert internal error (SSL alert number 80)
  app/models/mastodon_app.rb:108:in `revoke_token'
  app/controllers/settings_controller.rb:226:in `mastodon_disconnect'
  app/controllers/application_controller.rb:198:in `n_plus_one_detection'
```

On our end we can rescue the exceptions and delete the linked account from our user profile. Instead of the regular success message, let's add a sentence like `We encountered an error when trying to unlink from the Mastodon instance, so if it's still up you may need to go to Settings -> Account -> Authorized Apps to remove the "lobste.rs" entry.`

Because Mastodon instance URLs are the same, we could even interpolate their instance name to link directly to `https://instance.name/oauth/authorized_applications`. There's a Rails hassle that it's hard to put HTML into `flash` messages, so this is only a nice-to-have.

**Comment by pushcx** [comment]
A third, different exception from the same user as the second, so that instance is likely gone as well:

```
  couldn't resolve [instance domain name redacted] (#<NoIPsError: NoIPsError>)
  app/models/mastodon_app.rb:108:in `revoke_token'
  app/controllers/settings_controller.rb:226:in `mastodon_disconnect'
  app/controllers/application_controller.rb:198:in `n_plus_one_detection'
```

**Comment by pushcx** [comment]
A fourth one:

```
A DNSError occurred in settings#mastodon_disconnect:

couldn't resolve social.octet-stream.net (#<NoIPsError: NoIPsError>)
app/models/mastodon_app.rb:108:in `revoke_token'
app/controllers/settings_controller.rb:226:in `mastodon_disconnect'
```

**Comment by pushcx** [comment]
Oh, and after touching this issue this morning I very belatedly realized I should just manually remove your mastodon instance, @thombles. So you’re set, and I’ll keep this bug open to track handling the exceptions.

**Comment by thombles** [comment]
My bad, I got impatient and tried it again knowing full well the issue was still open. :sweat_smile: Thank you for that.

**Comment by pushcx** [comment]
I fixed part of this in a49c3df9 and the other exception in 9f46134a. There will probably be more exceptions in this flow, but I'd rather handle them one-by-one as they arise than spend time searching those code paths for every possible exception.
