### ISSUE TITLE
Ironic exception about duplicate records in check_url_dupe

### ISSUE THREAD

**Issue by pushcx** [lobsters/lobsters#1402]
```
An ActiveRecord::RecordNotUnique occurred in stories#check_url_dupe:

  Trilogy::ProtocolError: 1062: Duplicate entry 'medium.com/leboncoin-tech-blog' for key 'index_origins_on_identifier' (trilogy_read_row)
  app/models/domain.rb:77:in `find_or_create_origin'
  app/models/story.rb:950:in `set_domain_and_origin'
  app/models/story.rb:992:in `url='
  app/controllers/stories_controller.rb:417:in `check_url_dupe'
  app/controllers/application_controller.rb:198:in `n_plus_one_detection'
```

The Origin objects are implicitly created in `find_or_create_origin` so perhaos it's failing to find an existing origin, or perhaps there's a race condition because the frontend is firing `check_url_dupe` twice. Either way this is an uncommon intermittent error.

**Comment by caius** [comment]
I poked at this a bit but struggled to write a spec to reproduce it on the main branch. My vague recollection is there's a race condition between validation & database uniqueness being enforced, where two processes can race to the same record without erroring at the ActiveRecord layer.

As a fix, I added `rescue ActiveRecord::RecordNotUnique` with `retry` (one attempt) in `Domain#find_or_create_origin` so if we see the error raised we just go find the record again, because this time it'll succeed (otherwise the database can't have raised the error). That'll work for anything that's calling `Domain#find_or_create_origin` not just the StoryController then too.

Something in my RSpec spies isn't working as expected though, I thought I could `allow()` a raise, then follow it up with an `allow().and_call_original` so we raise the first time the method is called, then continue execution as allowed. That wasn't happening though, either I got the original method always called or the error always raised. I'm probably holding the APIs wrong somehow, just wanted to note how I'd approached it in case someone else picked it up before me.

**Comment by pushcx** [comment]
Looks like we have a new version of this bug. I'll ping @dreig if you want to take another crack at it, but you certainly aren't obligated to.

```
An ActiveRecord::RecordInvalid occurred in stories#fetch_url_attributes:

  Validation failed: Identifier has already been taken
  app/models/domain.rb:77:in `find_or_create_origin'
  app/models/story.rb:950:in `set_domain_and_origin'
  app/models/story.rb:992:in `url='
  app/controllers/stories_controller.rb:87:in `fetch_url_attributes'
  app/controllers/application_controller.rb:204:in `n_plus_one_detection'
```

The origin (a github username) did not exist before the user started interacting with the story submission form. Its `created_at` timestamp matches the exception to the second (the exception doesn't have milliseconds).

Here's the server logs, with user info redacted:

```
{"method":"POST","path":"/stories/fetch_url_attributes","format":"json","controller":"StoriesController","action":"fetch_url_attributes","status":422,"allocations":2780,"duration":21.07,"view":0.0,"db":7.08,"timestamp":"2025-01-06T17:40:31.854Z","params":{"fetch_url":"https://github.com/kartva/keymashed"},"exception":"ActiveRecord::RecordInvalid","exception_message":"Validation failed: Identifier has already been taken","remote_ip":"[redacted]","user_id":[redacted],"username":"eBPF"}
{"method":"POST","path":"/stories/check_url_dupe","format":"*/*","controller":"StoriesController","action":"check_url_dupe","status":200,"allocations":6007,"duration":80.9,"view":2.95,"db":62.43,"timestamp":"2025-01-06T17:40:31.908Z","params":{"authenticity_token":"[FILTERED]","story":{"url":"https://github.com/kartva/keymashed","title":"","tags_a":[""],"description":"","user_is_author":"0","user_is_following":"0"}},"exception":null,"exception_message":null,"remote_ip":"[redacted]","user_id":[redacted],"username":"eBPF"}
{"method":"POST","path":"/stories/check_url_dupe","format":"*/*","controller":"StoriesController","action":"check_url_dupe","status":200,"allocations":4249,"duration":19.95,"view":2.85,"db":8.6,"timestamp":"2025-01-06T17:40:52.139Z","params":{"authenticity_token":"[FILTERED]","story":{"url":"https://github.com/kartva/keymashed","title":"","tags_a":[""],"description":"","user_is_author":"0","user_is_following":"0"}},"exception":null,"exception_message":null,"remote_ip":"[redacted]","user_id":[redacted],"username":"eBPF"}
{"method":"POST","path":"/stories/check_url_dupe","format":"*/*","controller":"StoriesController","action":"check_url_dupe","status":200,"allocations":4250,"duration":19.85,"view":2.96,"db":7.58,"timestamp":"2025-01-06T17:40:56.981Z","params":{"authenticity_token":"[FILTERED]","story":{"url":"https://github.com/kartva/keymashed","title":"","tags_a":[""],"description":"","user_is_author":"0","user_is_following":"0"}},"exception":null,"exception_message":null,"remote_ip":"[redacted]","user_id":[redacted],"username":"eBPF"}
{"method":"POST","path":"/stories/fetch_url_attributes","format":"json","controller":"StoriesController","action":"fetch_url_attributes","status":200,"allocations":5974,"duration":553.5,"view":0.16,"db":5.6,"timestamp":"2025-01-06T17:40:57.517Z","params":{"fetch_url":"https://github.com/kartva/keymashed"},"exception":null,"exception_message":null,"remote_ip":"[redacted]","user_id":[redacted],"username":"eBPF"}
{"method":"POST","path":"/stories","format":"html","controller":"StoriesController","action":"create","status":302,"allocations":15541,"duration":122.54,"view":0.0,"db":56.48,"location":"https://lobste.rs/s/aftrmz/keymashed_mash_your_keyboard_make_your","timestamp":"2025-01-06T17:41:36.133Z","params":{"authenticity_token":"[FILTERED]","story":{"url":"https://github.com/kartva/keymashed","title":"keymashed: Mash your keyboard to make your internet better","tags_a":["","art","rust"],"description":"","user_is_author":"0","user_is_following":"0"},"commit":"Submit"},"exception":null,"exception_message":null,"remote_ip":"[redacted]","user_id":[redacted],"username":"eBPF"}
```

**Comment by dreig** [comment]
Thanks for posting the logs.
Frankly, I was having some trouble imagining what circumstance might lead to two concurrent requests to `/stories/check_url_dupe`, but now it's quite apparent what's triggering the error from the UI. I believe the following two requests are relevant:
```
{"method":"POST","path":"/stories/fetch_url_attributes","format":"json","controller":"StoriesController","action":"fetch_url_attributes","status":422,"allocations":2780,"duration":21.07,"view":0.0,"db":7.08,"timestamp":"2025-01-06T17:40:31.854Z","params":{"fetch_url":"https://github.com/kartva/keymashed"},"exception":"ActiveRecord::RecordInvalid","exception_message":"Validation failed: Identifier has already been taken","remote_ip":"[redacted]","user_id":[redacted],"username":"eBPF"}
{"method":"POST","path":"/stories/check_url_dupe","format":"*/*","controller":"StoriesController","action":"check_url_dupe","status":200,"allocations":6007,"duration":80.9,"view":2.95,"db":62.43,"timestamp":"2025-01-06T17:40:31.908Z","params":{"authenticity_token":"[FILTERED]","story":{"url":"https://github.com/kartva/keymashed","title":"","tags_a":[""],"description":"","user_is_author":"0","user_is_following":"0"}},"exception":null,"exception_message":null,"remote_ip":"[redacted]","user_id":[redacted],"username":"eBPF"}
```
In the story creation form, when the user clicks `Fetch Title`, the story URL input goes out of focus and triggers a request to `/stories/check_url_dupe`. These two requests then may generate a race condition on creating an Origin record.

Let me see if I can come up with a fix to this.

**Comment by pushcx** [comment]
I haven't seen this in a while, I think some recent work I did in Domain and Origin solved it.
