### ISSUE TITLE
enable bootsnap

### ISSUE THREAD

**Issue by thomasdziedzic-pd** [lobsters/lobsters#512]
This is part of the rails 5.2 upgrade.

See https://github.com/lobsters/lobsters/pull/498/commits/4d2b9ec0ece9d2dbb00a6961d2619d3fcc4f98f8

**Comment by pushcx** [comment]
So... I'm not seeing an explanation in the [upgrade docs](http://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#bootsnap). What is this thing, and why do we want it?

**Comment by thomasdziedzic-pd** [comment]
http://guides.rubyonrails.org/upgrading_ruby_on_rails.html#bootsnap

related rails pr: https://github.com/rails/rails/pull/29313

Basically it's optional, but should help with speeding up boot times and it's included in the default generated rails project moving forward.

**Comment by pushcx** [comment]
Huh. Seems worth a shot. I knew I'd seen the name before; it turned up in #292 which was a local config error.

This feels like the sort of feature I've seen cause subtle issues with code not reloading or other maddening things, so if this comment is being read by someone in the future who's dealing with frustrating, subtle issues, I'm open to disabling or removing this.

**Comment by pushcx** [comment]
Yep, broke prod. Reverting. Lobsters is a small app with reasonable startup time, so this is not worth a bunch of hassling around with prod permission issues.

It looks like [this bug](https://github.com/Shopify/bootsnap/issues/77): 

```
[WARNING] Could not load command "rails/commands/console/console_command". Error: Permission denied - bs_fetch:atomic_write_cache_file:open.                                                  [0/17]
/srv/lobste.rs/http/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/compile_cache/iseq.rb:37:in `fetch'                                                                                  
/srv/lobste.rs/http/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/compile_cache/iseq.rb:37:in `load_iseq'                                                                              
/srv/lobste.rs/http/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'                                                           
/srv/lobste.rs/http/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'                                
/srv/lobste.rs/http/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'                                                            
/srv/lobste.rs/http/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'                                         
/srv/lobste.rs/http/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'                                                           
/srv/lobste.rs/http/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `block in require'                                                                 
/srv/lobste.rs/http/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'                                                                  
/srv/lobste.rs/http/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'                                                                          
/srv/lobste.rs/http/vendor/bundle/ruby/2.3.0/gems/railties-5.2.0/lib/rails/command/behavior.rb:84:in `block (2 levels) in lookup'                                                                  
/srv/lobste.rs/http/vendor/bundle/ruby/2.3.0/gems/railties-5.2.0/lib/rails/command/behavior.rb:80:in `each'                                                                                        
/srv/lobste.rs/http/vendor/bundle/ruby/2.3.0/gems/railties-5.2.0/lib/rails/command/behavior.rb:80:in `block in lookup'                                                                             
/srv/lobste.rs/http/vendor/bundle/ruby/2.3.0/gems/railties-5.2.0/lib/rails/command/behavior.rb:79:in `each'                                                                                        
/srv/lobste.rs/http/vendor/bundle/ruby/2.3.0/gems/railties-5.2.0/lib/rails/command/behavior.rb:79:in `lookup'                                                                                      
/srv/lobste.rs/http/vendor/bundle/ruby/2.3.0/gems/railties-5.2.0/lib/rails/command.rb:70:in `find_by_namespace'                                                                                    
/srv/lobste.rs/http/vendor/bundle/ruby/2.3.0/gems/railties-5.2.0/lib/rails/command.rb:44:in `invoke'                                                                                               
/srv/lobste.rs/http/vendor/bundle/ruby/2.3.0/gems/railties-5.2.0/lib/rails/commands.rb:18:in `<main>'                                                                                              
/srv/lobste.rs/http/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'                                                           
/srv/lobste.rs/http/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'                                
/srv/lobste.rs/http/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'                                                            
/srv/lobste.rs/http/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'                                         
/srv/lobste.rs/http/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'                                                           
/srv/lobste.rs/http/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `block in require'                                                                 
/srv/lobste.rs/http/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'                                                                  
/srv/lobste.rs/http/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'                                                                          
bin/rails:4:in `<main>'
rails aborted!
Don't know how to build task 'console' (see --tasks)
/srv/lobste.rs/http/vendor/bundle/ruby/2.3.0/gems/railties-5.2.0/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'                                                                  
/srv/lobste.rs/http/vendor/bundle/ruby/2.3.0/gems/railties-5.2.0/lib/rails/commands/rake/rake_command.rb:20:in `perform'                                                                           
/srv/lobste.rs/http/vendor/bundle/ruby/2.3.0/gems/railties-5.2.0/lib/rails/command.rb:48:in `invoke'                                                                                               
/srv/lobste.rs/http/vendor/bundle/ruby/2.3.0/gems/railties-5.2.0/lib/rails/commands.rb:18:in `<main>'                                                                                              
/srv/lobste.rs/http/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'                                                           
/srv/lobste.rs/http/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'                                
/srv/lobste.rs/http/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'                                                            
/srv/lobste.rs/http/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'                                         
/srv/lobste.rs/http/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'                                                           
/srv/lobste.rs/http/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `block in require'                                                                 
/srv/lobste.rs/http/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'                                                                  
/srv/lobste.rs/http/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'                                                                          
bin/rails:4:in `<main>'
(See full trace by running task with --trace)
```
