### ISSUE TITLE
Issues automating install of rails / db seeding

### ISSUE THREAD

**Issue by jondkelley** [lobsters/lobsters#620]
I'm working on contributing a vagrantfile once I learn the basic setup / dependencies.

Things work, but when I run rails it says the error below.
db schema creation, seeding, etc went fine with mysql.
i may need redis and imagemagik, but this error is odd

## I tried this on ubuntu precise:

After ruby exception comment block is my entire script of installation (bash) to this point.
MySQL 5.7 was preconfigured.

```
rails server
=> Booting WEBrick
=> Rails 5.2.0 application starting in production on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
Exiting
/usr/share/lobsters/extras/prohibit_form_for_and_form_tag.rb:4:in `<module:Style>': superclass must be a Class (Module given) (TypeError)
	from /usr/share/lobsters/extras/prohibit_form_for_and_form_tag.rb:3:in `<module:Cop>'
	from /usr/share/lobsters/extras/prohibit_form_for_and_form_tag.rb:2:in `<module:RuboCop>'
	from /usr/share/lobsters/extras/prohibit_form_for_and_form_tag.rb:1:in `<top (required)>'
	from /home/vagrant/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'
	from /home/vagrant/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `block in require'
	from /home/vagrant/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
	from /home/vagrant/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'
	from /home/vagrant/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:370:in `block in require_or_load'
	from /home/vagrant/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:37:in `block in load_interlock'
	from /home/vagrant/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.2.0/lib/active_support/dependencies/interlock.rb:14:in `block in loadin
```

```
#!/bin/bash

# Install rbenv if it's missing
which "rbenv" >/dev/null 2>&1
if [ $? -ne 0 ]; then
    # gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
    # apt-get install -y build-essential; \
    #     apt-get install -y openssl libreadline6 libreadline6-dev curl zlib1g zlib1g-dev libssl-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt-dev autoconf libc6-dev ncurses-dev automake libtool bison subversion pkg-config; \
    # 		apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*; \
    # 		curl -sSL https://rvm.io/mpapis.asc | gpg --import -; \
    # 		curl -L https://get.rvm.io | bash -s stable; \
    # 		/bin/bash -l -c "rvm requirements"; \
    #     /bin/bash -l -c "rvm install $RUBY_VERSION"; \
    #     /bin/bash -l -c "gem install bundler --no-ri --no-rdoc"; \
    # 		/bin/bash -l -c "rvm cleanup all"; \
    # 		apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*; \
    sudo apt-get install -y git-core
    sudo apt-get install -y autoconf bison build-essential libssl-dev libyaml-dev libreadline6-dev zlib1g-dev libncurses5-dev libffi-dev libgdbm3 libgdbm-dev
    git clone https://github.com/rbenv/rbenv.git ~/.rbenv
    echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
    echo 'eval "$(rbenv init -)"' >> ~/.bashrc
    source ~/.bashrc
    git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
    rbenv install -l
    rbenv install 2.3.3
    rbenv global 2.3.3
    echo "gem: --no-document" > ~/.gemrc
    rbenv rehash
    gem install bundler
fi

# Install node js if it's missing
which "node" >/dev/null 2>&1
if [ $? -ne 0 ]; then
    sudo apt-get install  -y nodejs
fi

# Prepare application dependecies
cd /usr/share/lobsters/
bundle install
gem install rails -v 5.2.0
gem install mysql
gem install listen
export RAILS_ENV=production
rails db:schema:load
rails db:seed
rails fake_data
rails server
```

**Comment by alanpost** [comment]
Are you having the same or a variation of the problem in #599?

**Comment by jondkelley** [comment]
Yep that does it. Thanks. It's been a while away from ruby!
I'll close this issue, and if I get a sweet vagrant instance going that installs via puppet, I'll share.

I just needed the dev ruby depends, and dpkg  `libsqlite3-dev`

```
vagrant@lobster:/usr/share/lobsters$ rails server
=> Booting WEBrick
=> Rails 5.2.1 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
[2018-12-12 02:28:09] INFO  WEBrick 1.3.1
[2018-12-12 02:28:09] INFO  ruby 2.3.3 (2016-11-21) [x86_64-linux]
[2018-12-12 02:28:09] INFO  WEBrick::HTTPServer#start: pid=20226 port=3000
```
