### ISSUE TITLE
markdown test only works when domain is example.com

### ISSUE THREAD

**Issue by NattyNarwhal** [lobsters/lobsters#709]
This test should be aware of what the current site domain is set to, as to not cause noise when you run it.

```
Failures:

  1) Markdowner turns @username into a link if @username exists
     Failure/Error:
       expect(Markdowner.to_html("hi @blahblah test"))
         .to eq("<p>hi <a href=\"https://example.com/u/blahblah\" rel=\"nofollow\">" +
                "@blahblah</a> test</p>\n")
     
       expected: "<p>hi <a href=\"https://example.com/u/blahblah\" rel=\"nofollow\">@blahblah</a> test</p>\n"
            got: "<p>hi <a href=\"http://localhost:3000/u/blahblah\" rel=\"nofollow\">@blahblah</a> test</p>\n"
     
       (compared using ==)
     
       Diff:
       @@ -1,2 +1,2 @@
       -<p>hi <a href="https://example.com/u/blahblah" rel="nofollow">@blahblah</a> test</p>
       +<p>hi <a href="http://localhost:3000/u/blahblah" rel="nofollow">@blahblah</a> test</p>
       
     # ./spec/models/markdowner_spec.rb:12:in `block (2 levels) in <top (required)>'
```

**Comment by pushcx** [comment]
Huh, this is an odd bug. I'd always expect this to be `example.com` in test mode. Are you deliberately running the tests in dev/prod mode? Did you maybe edit your domain into `config/application.rb` instead of overriding it in `config/initalizers/production.rb`?

**Comment by NattyNarwhal** [comment]
Just using `GEM_HOME=vendor/bundle/ruby/2.6.0 bundle exec rspec`. `config/application.rb` seems unmodified.

**Comment by pushcx** [comment]
Hm. Try `RAILS_ENV=test GEM_HOME=vendor/bundle/ruby/2.6.0 bundle exec rspec`. My best guess is that you've created `config/initalizers/production.rb` and something in your env is running the tests in `production` mode instead of `test`.

**Comment by NattyNarwhal** [comment]
```
[calvin@salient lobsters]$ RAILS_ENV=test GEM_HOME=vendor/bundle/ruby/2.6.0 bundle exec rspec
.................................................................................F...........................................................................................

Failures:

  1) Markdowner turns @username into a link if @username exists
     Failure/Error:
       expect(Markdowner.to_html("hi @blahblah test"))
         .to eq("<p>hi <a href=\"https://example.com/u/blahblah\" rel=\"nofollow\">" +
                "@blahblah</a> test</p>\n")
     
       expected: "<p>hi <a href=\"https://example.com/u/blahblah\" rel=\"nofollow\">@blahblah</a> test</p>\n"
            got: "<p>hi <a href=\"http://localhost:3000/u/blahblah\" rel=\"nofollow\">@blahblah</a> test</p>\n"
     
       (compared using ==)
     
       Diff:
       @@ -1,2 +1,2 @@
       -<p>hi <a href="https://example.com/u/blahblah" rel="nofollow">@blahblah</a> test</p>
       +<p>hi <a href="http://localhost:3000/u/blahblah" rel="nofollow">@blahblah</a> test</p>
       
     # ./spec/models/markdowner_spec.rb:12:in `block (2 levels) in <top (required)>'

Finished in 10.25 seconds (files took 2.08 seconds to load)
173 examples, 1 failure

Failed examples:

rspec ./spec/models/markdowner_spec.rb:9 # Markdowner turns @username into a link if @username exists

[calvin@salient lobsters]$ cat config/initalizers/production.rb
cat: config/initalizers/production.rb: No such file or directory
```

**Comment by pushcx** [comment]
I'm puzzled where this could be coming from. Can you `grep -r localhost app config`? I only see one hit, in the (unused, default) `config/cable.yml`. If you see anything else, that's worth checking git history for.

**Comment by NattyNarwhal** [comment]
```
$ grep -r localhost app config
config/cable.yml:  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
config/initializers/production.rb:    "localhost:3000"
```

The config file is set up per the instructions.

**Comment by pushcx** [comment]
OK, so we didn't catch it in the last round because I typod `initializers` as `initalizers`. You only need to set up that file on your production host. In cb2bbe8 I improved the README and expanded the scope of the `if Rails.env.production?` conditional that exists to catch this case. If you bring the `if` change in to your `production.rb` your tests should go green again. Sorry about this confusion - the instructions assumed a significant familiarity with Rails conventions.

**Comment by pushcx** [comment]
Discussed in chat. That sorted out the issue.
