### ISSUE TITLE
mail_new_activity undefined method on empty database

### ISSUE THREAD

**Issue by alanpost** [lobsters/lobsters#731]
I've got a new Lobsters instance, with a single user but no stories, tags, comments, etc.  When I run the mail_new_activity.rb script, I get the following error:

    script/mail_new_activity.rb:69:in `<main>': undefined method `id' for nil:NilClass (NoMethodError)
    error at line 14, in call to /usr/local/bin/bundle exec ruby script/mail_new_activity.rb

This is line 69:

    last_story_id = (Keystore.value_for(LAST_STORY_KEY) || Story.last.id).to_i

Is it possible to make this script no-op silently when there are no stories?

**Comment by alanpost** [comment]
Upon submitting stories, a similar error related to missing comments:

    script/mail_new_activity.rb:146:in `<main>': undefined method `id' for nil:NilClass (NoMethodError)
    error at line 14, in call to /usr/local/bin/bundle exec ruby script/mail_new_activity.rb

This is lines 145-146:

    last_comment_id = (Keystore.value_for(LAST_COMMENT_KEY) ||
      Comment.last.id).to_i
