### ISSUE TITLE
NotNullViolation replacing deadlocks

### ISSUE THREAD

**Issue by pushcx** [lobsters/lobsters#783]
Over in https://github.com/lobsters/lobsters-ansible/issues/39 I've been trying to puzzle out why we infrequently get deadlocks saving comments. Since that deploy I've gotten five exceptions during comment saving complaining that the `created_at` field is null. The frequency of ~1 per week is the same as the deadlocks, so I feel confident saying that all I've managed is to convert one really frustrating exception into a different frustrating exception.

There's some slight differences:

```
An ActiveRecord::NotNullViolation occurred in comments#create:

  Mysql2::Error: Field 'created_at' doesn't have a default value: INSERT INTO `comments` (`short_id`) VALUES
('s4b7of')
  app/controllers/comments_controller.rb:50:in `create'

---

  Mysql2::Error: Field 'created_at' doesn't have a default value: INSERT INTO `comments` (`short_id`, `thread_id`)
VALUES ('uo0mph', 259640)
  app/controllers/comments_controller.rb:50:in `create'

---

  Mysql2::Error: Field 'created_at' doesn't have a default value: INSERT INTO `comments` (`short_id`) VALUES
('mhlzvz')
  app/controllers/comments_controller.rb:50:in `create'

---

  Mysql2::Error: Field 'created_at' doesn't have a default value: INSERT INTO `comments` (`short_id`) VALUES
('acipp1')
  app/controllers/comments_controller.rb:50:in `create'

---

  Mysql2::Error: Field 'created_at' doesn't have a default value: INSERT INTO `comments` (`short_id`) VALUES
('ytulou')
  app/controllers/comments_controller.rb:50:in `create'
```

I suspect this mentions `created_at` because it's the first field on the table in `db/schema.rb`. It's really odd to me that they are only inserting `short_id` instead of all the fields. It's also odd that one includes `thread_id`, looks like that's the only one of the five that's a top-level comment rather than a reply to an existing comment. That feels important.

Like the deadlocks, they're all perfectly normal comment postings, no pattern in time of day, author, browser, etc. I've contacted a few of the users, they've all confirmed that they tried to save a comment, it didn't work, they tried again in a minute or in a different browser and it did.

Ideas? _Something_ weird is happening here.

**Comment by pushcx** [comment]
This stopped, I think with the Rails 6 update.
