### ISSUE TITLE
Mysql2::Error: Field 'created_at' doesn't have a default value

### ISSUE THREAD

**Issue by alanpost** [lobsters/lobsters#817]
This morning three separate exceptions related to posting a comment:

> An ActiveRecord::NotNullViolation occurred in comments#create:
> Mysql2::Error: Field 'created_at' doesn't have a default value: INSERT INTO `comments` (`short_id`) VALUES ('irohkx')
> app/controllers/comments_controller.rb:51:in `create'

By appearance the data sent in the request is missing, partial or truncated.  Reaching out to the user whose comment submission triggered two of the exceptions:

> not surprising -- I was on the subway, lost connection a couple of times mid post.
> hit the 'reply' button a few times, and when I got the connection back, multiple reply boxes appeared.

In this case the user did eventually get their comment posted.  This happened to one other user today and probably occasionally in the past--this is a tracking ticket for the phenomena.

**Comment by alanpost** [comment]
Looking through my exception log, this exception was raised twice on December 15th, once each on December 14th, 11th, and 10th.  Four times in November and thrice in October 2019.

**Comment by pushcx** [comment]
This is a really disconcerting bug to me: not only do I not see how it's possible to end up in this state, it breaks comment posting which is roughly the most important thing on the site.

I hesitate to point fingers upstream, but I wonder if this could be a Rails bug. The exception notifications look like complete comments posted normally. `created_at` should have been automatically filled by Rails; the call to `comment.save` even follows a check to `comment.valid?`.

I don't see any conspicuous commits in the month or two before this started, but on 2019-06-29 we bumped our Rails version to 5.2.3, maybe we picked up a bug. I've bumped us to 5.2.4.1. If we don't see this again in six months I'll just close it.

**Comment by pushcx** [comment]
One more a few minutes ago, unfortunately.

**Comment by pushcx** [comment]
Saw this again this morning. Happened three times but the user was able to submit:

>   Mysql2::Error: Field 'created_at' doesn't have a default value: INSERT INTO `comments` (`short_id`) VALUES
('nko0cx')

**Comment by pushcx** [comment]
It occurred to me to check the timestamp - all three failure and the successful comment happened in the same second. So we apparently also have some kind of client-side bug (js or browser) that's attempting to submit a comment multiple times.

```
I, [2020-07-09T12:22:34.660849 #2626851]  INFO -- : [9733fdbe-4260-42df-8b4a-f0a1d7a1568e] Started POST "/comments" for [user ip] at 2020-07-09 12:22:34 +0000
I, [2020-07-09T12:22:34.661677 #2626826]  INFO -- : [796d7d78-1de7-4875-a303-bb30e213dac4] Started POST "/comments" for [user ip] at 2020-07-09 12:22:34 +0000
I, [2020-07-09T12:22:34.662892 #2626864]  INFO -- : [7700618c-50a6-46aa-8fef-190e69816bcd] Started POST "/comments" for [user ip] at 2020-07-09 12:22:34 +0000
I, [2020-07-09T12:22:34.663704 #2626826]  INFO -- : [796d7d78-1de7-4875-a303-bb30e213dac4] Processing by CommentsController#create as */*
I, [2020-07-09T12:22:34.663704 #2626838]  INFO -- : [3414acbb-76d9-4c77-8911-0b80e4774519] Started POST "/comments" for [user ip] at 2020-07-09 12:22:34 +0000
I, [2020-07-09T12:22:34.663836 #2626826]  INFO -- : [796d7d78-1de7-4875-a303-bb30e213dac4]   Parameters: {"utf8"=>"✓", "authenticity_token"=>"[user token]", "story_id"=>"kvkbh3", "parent_comment_short_id"=>"czybv1", "comment"=>"> such as youtube’s &disable_polymer=1,\r\n\r\nDo you just append this to the URL? It do
esn't seem to change anything on my system.", "show_tree_lines"=>"true"}
I, [2020-07-09T12:22:34.664815 #2626864]  INFO -- : [7700618c-50a6-46aa-8fef-190e69816bcd] Processing by CommentsController#create as */*
I, [2020-07-09T12:22:34.664815 #2626838]  INFO -- : [3414acbb-76d9-4c77-8911-0b80e4774519] Processing by CommentsController#create as */*
I, [2020-07-09T12:22:34.665149 #2626864]  INFO -- : [7700618c-50a6-46aa-8fef-190e69816bcd]   Parameters: {"utf8"=>"✓", "authenticity_token"=>"[user token]", "story_id"=>"kvkbh3", "parent_comment_short_id"=>"czybv1", "comment"=>"> such as youtube’s &disable_polymer=1,\r\n\r\nDo you just append this to the URL? It do
esn't seem to change anything on my system.", "show_tree_lines"=>"true"}
I, [2020-07-09T12:22:34.665149 #2626838]  INFO -- : [3414acbb-76d9-4c77-8911-0b80e4774519]   Parameters: {"utf8"=>"✓", "authenticity_token"=>"[user token]", "story_id"=>"kvkbh3", "parent_comment_short_id"=>"czybv1", "comment"=>"> such as youtube’s &disable_polymer=1,\r\n\r\nDo you just append this to the URL? It do
esn't seem to change anything on my system.", "show_tree_lines"=>"true"}
I, [2020-07-09T12:22:34.668292 #2626826]  INFO -- : [796d7d78-1de7-4875-a303-bb30e213dac4]   Request [user ip] POST /comments user: 8543 zge
I, [2020-07-09T12:22:34.668477 #2626851]  INFO -- : [9733fdbe-4260-42df-8b4a-f0a1d7a1568e] Processing by CommentsController#create as */*
I, [2020-07-09T12:22:34.668811 #2626838]  INFO -- : [3414acbb-76d9-4c77-8911-0b80e4774519]   Request [user ip] POST /comments user: 8543 zge
I, [2020-07-09T12:22:34.668858 #2626851]  INFO -- : [9733fdbe-4260-42df-8b4a-f0a1d7a1568e]   Parameters: {"utf8"=>"✓", "authenticity_token"=>"[user token]", "story_id"=>"kvkbh3", "parent_comment_short_id"=>"czybv1", "comment"=>"> such as youtube’s &disable_polymer=1,\r\n\r\nDo you just append this to the URL? It do
esn't seem to change anything on my system.", "show_tree_lines"=>"true"}
I, [2020-07-09T12:22:34.669881 #2626864]  INFO -- : [7700618c-50a6-46aa-8fef-190e69816bcd]   Request [user ip] POST /comments user: 8543 zge
I, [2020-07-09T12:22:34.671677 #2626851]  INFO -- : [9733fdbe-4260-42df-8b4a-f0a1d7a1568e]   Request [user ip] POST /comments user: 8543 zge
W, [2020-07-09T12:22:34.709839 #2626826]  WARN -- : [796d7d78-1de7-4875-a303-bb30e213dac4] Transaction isolation conflict detected. Retrying for the 1-st time...
W, [2020-07-09T12:22:34.710310 #2626864]  WARN -- : [7700618c-50a6-46aa-8fef-190e69816bcd] Transaction isolation conflict detected. Retrying for the 1-st time...
W, [2020-07-09T12:22:34.711047 #2626851]  WARN -- : [9733fdbe-4260-42df-8b4a-f0a1d7a1568e] Transaction isolation conflict detected. Retrying for the 1-st time...
I, [2020-07-09T12:22:34.717164 #2626826]  INFO -- : [796d7d78-1de7-4875-a303-bb30e213dac4] Completed 500 Internal Server Error in 53ms (ActiveRecord: 19.6ms)
I, [2020-07-09T12:22:34.718074 #2626864]  INFO -- : [7700618c-50a6-46aa-8fef-190e69816bcd] Completed 500 Internal Server Error in 53ms (ActiveRecord: 22.3ms)
I, [2020-07-09T12:22:34.718612 #2626851]  INFO -- : [9733fdbe-4260-42df-8b4a-f0a1d7a1568e] Completed 500 Internal Server Error in 50ms (ActiveRecord: 15.0ms)
I, [2020-07-09T12:22:34.730206 #2626838]  INFO -- : [3414acbb-76d9-4c77-8911-0b80e4774519] Completed 200 OK in 65ms (Views: 4.4ms | ActiveRecord: 29.0ms)
I, [2020-07-09T12:22:34.767348 #2626864]  INFO -- : [7700618c-50a6-46aa-8fef-190e69816bcd] Sent mail to [admin email addressed] (19.5ms)
I, [2020-07-09T12:22:34.767685 #2626851]  INFO -- : [9733fdbe-4260-42df-8b4a-f0a1d7a1568e] Sent mail to [admin email addressed] (19.9ms)
F, [2020-07-09T12:22:34.768779 #2626864] FATAL -- : [7700618c-50a6-46aa-8fef-190e69816bcd]
F, [2020-07-09T12:22:34.768860 #2626864] FATAL -- : [7700618c-50a6-46aa-8fef-190e69816bcd] ActiveRecord::NotNullViolation (Mysql2::Error: Field 'created_at' doesn't have a default value: INSERT IN
TO `comments` (`short_id`) VALUES ('ezkuqb')):
F, [2020-07-09T12:22:34.768917 #2626864] FATAL -- : [7700618c-50a6-46aa-8fef-190e69816bcd]
F, [2020-07-09T12:22:34.768990 #2626864] FATAL -- : [7700618c-50a6-46aa-8fef-190e69816bcd] app/controllers/comments_controller.rb:51:in `create'
[7700618c-50a6-46aa-8fef-190e69816bcd] config/initializers/production.rb:42:in `call'
F, [2020-07-09T12:22:34.769552 #2626851] FATAL -- : [9733fdbe-4260-42df-8b4a-f0a1d7a1568e]
F, [2020-07-09T12:22:34.769920 #2626851] FATAL -- : [9733fdbe-4260-42df-8b4a-f0a1d7a1568e] ActiveRecord::NotNullViolation (Mysql2::Error: Field 'created_at' doesn't have a default value: INSERT INTO `comments` (`short_id`) VALUES ('xiu9sw')):
F, [2020-07-09T12:22:34.770033 #2626851] FATAL -- : [9733fdbe-4260-42df-8b4a-f0a1d7a1568e]
F, [2020-07-09T12:22:34.770050 #2626851] FATAL -- : [9733fdbe-4260-42df-8b4a-f0a1d7a1568e] app/controllers/comments_controller.rb:51:in `create'
[9733fdbe-4260-42df-8b4a-f0a1d7a1568e] config/initializers/production.rb:42:in `call'
I, [2020-07-09T12:22:34.777701 #2626826]  INFO -- : [796d7d78-1de7-4875-a303-bb30e213dac4] Sent mail to [admin email addressed] (24.8ms)
F, [2020-07-09T12:22:34.779206 #2626826] FATAL -- : [796d7d78-1de7-4875-a303-bb30e213dac4]
F, [2020-07-09T12:22:34.779289 #2626826] FATAL -- : [796d7d78-1de7-4875-a303-bb30e213dac4] ActiveRecord::NotNullViolation (Mysql2::Error: Field 'created_at' doesn't have a default value: INSERT INTO `comments` (`short_id`) VALUES ('nko0cx')):
F, [2020-07-09T12:22:34.779347 #2626826] FATAL -- : [796d7d78-1de7-4875-a303-bb30e213dac4]
F, [2020-07-09T12:22:34.779657 #2626826] FATAL -- : [796d7d78-1de7-4875-a303-bb30e213dac4] app/controllers/comments_controller.rb:51:in `create'
[796d7d78-1de7-4875-a303-bb30e213dac4] config/initializers/production.rb:42:in `call'
```

**Comment by pushcx** [comment]
I asked the user if they saw anything odd in posting this:

> It just took a while, but I assumed it was a issue on my side because I just opened two other sites and they took just as long to load. I didn’t notice this at first, so I clicked on “Post” two or three times, but other than that, I didn’t notice anything.

**Comment by pushcx** [comment]
Not seen in years.
